# Backpacks — Pivot / Pedal / Pangea / Fleet / 08:01 / Field
CATEGORY = {
    "key": "Backpacks",
    "tab": "Backpacks",
    "title": "BACKPACKS",
    "snapshot": {
        "Category & moat": "DO's broadest, most scalable bag bet (Rs9Cr FY26 -> Rs26Cr FY27). Spans Value->Premium Rs1,349-3,999. Moat = design + tech-integration ('the tech brand's backpack'), not outdoor heritage or scale.",
        "Hero SKUs / price": "Pedal Daypack Rs1,349 (value entry) · Field Rs3,299 · Pivot Taiga Rs3,999 · Pangea (travel) · Fleet / 08:01",
        "Dominant TG — gender": "Male 64% / Female 36%  (DO's MOST gender-balanced audience)",
        "Dominant TG — age": "25-34 = 43% · 35-44 = 21% · 18-24 = 18% · 45+ = 18%   (18-44 = 83%)",
        "Dominant TG — geography": "MH 23 · KA 15 · DL 10 · GJ 8 · HR 7 · UP 7 · TN 6 · TG 6  (top-8 ~82%). Most geographically spread bag audience.",
        "Performance signal": "Category_DG (always-on) ~3.1x ROAS on ~Rs16.2L spend.",
        "Read": "Versatile everyday / work / college / commute / travel buyer. Women are a major segment, not just headroom. Expansion = win women on design, cross-sell from the tech base, and the frequent traveller (Pangea).",
    },
    "personas": [
        {
            "name": "Hybrid Work Commuter",
            "tg": "Dominant",
            "who": "25-34 professional, office+WFH hybrid, carries a laptop daily, values organisation and a professional look.",
            "trigger": "New job / old bag wearing out; needs one bag that works for office, commute and cafe-work.",
            "need": "A device-first backpack that protects the laptop, organises the everyday, and looks professional.",
            "pain": "Outdoor/school backpacks look wrong at work; laptop sags around loose in a soft bag.",
            "angle": "Pain point + Desired outcome",
            "sku": "Pivot Taiga Rs3,999 / Field Rs3,299",
            "reach": "Commute & 'what's in my bag' reels, professional 25-44 audiences, DO tech customers, feed",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't questioned his old college backpack", "Curiosity / Story",
                 "You upgraded the laptop, the phone, the desk — but you still carry a college backpack.", "BAB",
                 '"Your bag is the last thing you haven\'t upgraded."'),
                ("MOFU", "Problem-aware", "Frustrated bag looks unprofessional & disorganised", "Pain point",
                 "A soft, shapeless bag makes you look junior and lets your laptop bounce around loose.", "PAS",
                 '"Walking into a meeting with a school bag?"'),
                ("MOFU", "Solution-aware", "Wants a work-grade organised backpack", "Desired outcome",
                 "A design-led backpack with a padded 16-inch laptop bay and a place for every cable.", "FAB",
                 '"A backpack that respects your laptop."'),
                ("BOFU", "Product-aware", "Comparing Pivot vs Wildcraft / Mokobara", "Feature / Comparison",
                 "Pivot: protective 16-inch bay, structured organisation, premium finish — built by a tech brand.", "FAB",
                 '"The tech brand\'s backpack. Made for your devices."'),
                ("BOFU", "Most-aware", "Ready, wants the easy yes", "Offer / Trust",
                 "Carry sorted for work & commute. Free delivery, 30-day returns, warranty.", "4 U's",
                 '"Upgrade your carry. Free delivery."'),
            ],
        },
        {
            "name": "Campus Student",
            "tg": "Dominant",
            "who": "18-24 college student / early-career, carries books + laptop, wants durable but good-looking, on a budget.",
            "trigger": "Back-to-college season; old bag torn; wants something that lasts and looks current.",
            "need": "A durable, spacious, good-looking backpack that survives daily campus abuse.",
            "pain": "Cheap bags fall apart in a semester; nice ones feel out of budget.",
            "angle": "Curiosity / Desired outcome",
            "sku": "Field Rs3,299 / Fleet",
            "reach": "Campus UGC, back-to-college reels, 18-24 lookalikes, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; relatable campus moment", "Story / Curiosity",
                 "The bag you started college with won't survive the year. Ask your seniors.", "BAB",
                 '"POV: your bag strap gave up mid-semester."'),
                ("MOFU", "Problem-aware", "Bag torn / looks worn", "Pain point",
                 "Broken zips, torn straps, a sad-looking bag by month two — sound familiar?", "PAS",
                 '"Third bag this year? Let\'s fix that."'),
                ("MOFU", "Solution-aware", "Learns there's a durable-but-cool option", "Desired outcome",
                 "Field & Fleet: built to survive campus, spacious for books + laptop, looks actually good.", "FAB",
                 '"Built for campus. Looks like it isn\'t."'),
                ("BOFU", "Product-aware", "Comparing durability & look", "Feature / Comparison",
                 "Tough materials, a real laptop compartment, colours that don't scream 'school bag'.", "FAB",
                 '"Survives the year. Every year."'),
                ("BOFU", "Most-aware", "Ready, back-to-college timing", "Offer",
                 "Get sorted before term starts. Free delivery, easy returns.", "4 U's",
                 '"Back-to-college sorted. Ships free."'),
            ],
        },
        {
            "name": "Everyday Daypack Minimalist",
            "tg": "Dominant",
            "who": "Value-first buyer entering the brand on a compact, light daypack — commute, gym, errands, cycle.",
            "trigger": "Wants a light, no-fuss daypack for daily movement without a bulky laptop bag.",
            "need": "A compact, lightweight, well-made daypack at an accessible entry price.",
            "pain": "Big laptop backpacks are overkill for a light day; cheap daypacks look throwaway.",
            "angle": "Curiosity / Desired outcome",
            "sku": "Pedal Daypack Rs1,349 (value entry)",
            "reach": "Lo-fi lifestyle reels, value-intent & lookalike audiences, feed",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; light-carry provocation", "Curiosity",
                 "Not every day needs a big laptop backpack. Some days need almost nothing.", "BAB",
                 '"Carrying a suitcase-sized bag for a phone and a charger?"'),
                ("MOFU", "Problem-aware", "Big bag feels like overkill", "Pain point",
                 "Lugging a full backpack for a coffee run and a laptop-free day is exhausting.", "PAS",
                 '"Your bag weighs more than what\'s in it."'),
                ("MOFU", "Solution-aware", "Discovers a light premium daypack", "Desired outcome",
                 "Pedal: a compact, light daypack that holds the essentials and still looks premium.", "FAB",
                 '"Light bag. Premium feel."'),
                ("BOFU", "Product-aware", "Checking size & price", "Feature / Offer",
                 "Right-sized for daily movement, tough materials, an easy entry into DO — under Rs1,500.", "FAB",
                 '"Premium daypack. Entry price."'),
                ("BOFU", "Most-aware", "Ready, low-risk buy", "Offer",
                 "Your everyday, lighter. Free delivery, easy returns.", "4 U's",
                 '"Grab-and-go, sorted. Ships free."'),
            ],
        },
        {
            "name": "Design-First Woman",
            "tg": "Expansion",
            "who": "Woman professional / student (already 36% of buyers) under-served on design by outdoor & luggage brands.",
            "trigger": "Wants a work/college backpack that's comfortable AND aesthetic — made with her in mind.",
            "need": "A lighter, aesthetic, comfortable backpack that fits her frame and her style.",
            "pain": "Backpacks are designed for men — bulky, heavy, aesthetically ignored.",
            "angle": "Desired outcome (design) + Social proof",
            "sku": "Fleet / lighter Pivot, aesthetic colourways",
            "reach": "Female-creator design films, women lookalikes, Reels & Explore",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; design provocation", "Curiosity / Story",
                 "Every backpack looks like it was designed for a 6-foot man. Where's yours?", "BAB",
                 '"Backpacks weren\'t designed for you. This one is."'),
                ("MOFU", "Problem-aware", "Bags are heavy, bulky, not for her", "Pain point",
                 "Digging shoulders, boxy shapes, boring colours — the backpack aisle forgot women exist.", "PAS",
                 '"Why does your bag hurt by lunchtime?"'),
                ("MOFU", "Solution-aware", "Finds a design-led, lighter option", "Desired outcome",
                 "Lighter build, comfortable straps, aesthetic colourways — a backpack that fits her, not against her.", "FAB",
                 '"A backpack made for how you actually carry."'),
                ("BOFU", "Product-aware", "Choosing colour & fit", "Desired outcome / Social proof",
                 "Fleet in her palette — light, comfortable, laptop-safe, and genuinely good-looking.", "FAB",
                 '"The work bag on your feed. (styling it)"'),
                ("BOFU", "Most-aware", "Wants validation", "Social proof / Offer",
                 "Loved by women who carry a lot. Pick your colour, free delivery, easy returns.", "4 U's",
                 '"Designed for her. Ships free."'),
            ],
        },
        {
            "name": "Frequent Traveller",
            "tg": "Expansion",
            "who": "28-45 frequent flyer / weekend tripper, multi-device, wants carry-on-smart organisation.",
            "trigger": "Packing for a trip; hates checking in and juggling multiple bags.",
            "need": "One travel-ready backpack: carry-on friendly, organised, protects tech, opens flat.",
            "pain": "Regular backpacks aren't built for airports — no laptop quick-access, no packing logic.",
            "angle": "Comparison / Ultra-specific",
            "sku": "Pangea (travel)",
            "reach": "Travel & airport-intent audiences, packing-demo reels, comparison carousels",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; relatable travel pain", "Story / Curiosity",
                 "Two bags, a laptop out at security, and a jacket you're now carrying. Every single trip.", "BAB",
                 '"Airport security with you = a small circus."'),
                ("MOFU", "Problem-aware", "Frustrated by disorganised travel carry", "Pain point",
                 "Your everyday backpack wasn't built for airports — nothing has a place, nothing's quick.", "PAS",
                 '"Repacking your bag at the gate. Again."'),
                ("MOFU", "Solution-aware", "Wants a travel-smart backpack", "Comparison / Desired outcome",
                 "Pangea: opens flat like a case, quick-access laptop, packing compartments, carry-on sized.", "FAB",
                 '"One bag. Every trip. Opens like a suitcase."'),
                ("BOFU", "Product-aware", "Comparing capacity & features", "Feature / Comparison",
                 "Carry-on friendly, dedicated tech bay, luggage pass-through, tough travel materials.", "FAB",
                 '"Carry-on smart. Tech-safe. Trip-ready."'),
                ("BOFU", "Most-aware", "Ready, packing now", "Offer",
                 "Pack one, travel light. Free delivery before your trip.", "4 U's",
                 '"Pack once. Ships free before you fly."'),
            ],
        },
        {
            "name": "Tech-Base Cross-sell Loyalist",
            "tg": "Expansion",
            "who": "Existing DO case/charger customer — Apple-ecosystem professional who trusts the brand for tech.",
            "trigger": "Already owns DO tech accessories; sees a DO backpack that fits his devices & sleeve.",
            "need": "A backpack from a brand he already trusts, built to hold his exact device kit.",
            "pain": "Generic bags aren't designed around his laptop, sleeve, charger and organiser.",
            "angle": "Authority / Feature",
            "sku": "Pivot Taiga Rs3,999 (+ sleeve / organiser bundle)",
            "reach": "Retargeting DO tech buyers, email/CRM, 'complete your carry' bundle creative",
            "funnel": [
                ("TOFU", "Unaware", "Doesn't know DO makes bags", "Curiosity",
                 "You trust us for your case and charger. Wait till you see what we built to carry them.", "BAB",
                 '"The brand on your phone now makes your bag."'),
                ("MOFU", "Problem-aware", "His bag doesn't fit his device kit", "Pain point",
                 "Your devices are a system. Your bag is a random pocket that doesn't fit any of it.", "PAS",
                 '"Your tech is coordinated. Your bag isn\'t."'),
                ("MOFU", "Solution-aware", "Realises DO bag = device-first", "Desired outcome / Authority",
                 "A backpack designed around your 16-inch, your DO sleeve, organiser and charger — one system.", "FAB",
                 '"A bag built around your exact kit."'),
                ("BOFU", "Product-aware", "Evaluating the ecosystem bundle", "Feature / Authority",
                 "Pivot + DO sleeve + tech organiser = your whole carry, coordinated and protected.", "FAB",
                 '"Complete your carry. One ecosystem."'),
                ("BOFU", "Most-aware", "Ready, warm to brand", "Offer",
                 "Bundle the bag with your sleeve & organiser and save. Free delivery for our customers.", "4 U's",
                 '"Complete the setup. Bundle & save."'),
            ],
        },
    ],
}
