# Wireless Chargers — Node / Surge / Loft
CATEGORY = {
    "key": "Wireless Chargers",
    "tab": "Wireless Chargers",
    "title": "NODE · WIRELESS CHARGERS",
    "snapshot": {
        "Category & moat": "Nascent, fast-growing premium tier (Rs4Cr FY26 -> Rs20Cr FY27, part category-creation). Premium+super-premium Rs4,499-7,999. Moat = own the Qi2.2 'fastest wireless' story + premium design; ~4.2x ROAS on tiny spend = under-funded.",
        "Hero SKUs / price": "Surge Rs4,499 (single-coil MagSafe) · Surge Foldaway Rs7,999 (3-in-1) · Node ecosystem (3-in-1 Qi2.2) · Loft 65W station",
        "Dominant TG — gender": "Male 81% / Female 19%",
        "Dominant TG — age": "25-34 = 51% (core) · 35-44 = 20% · 18-24 = 22% · 45+ = 6%   (25-44 = 71%)",
        "Dominant TG — geography": "MH 24 · KA 15 · DL 9 · GJ 8 · HR 7 · UP 7 · TG 6 · TN 6  (top-8 ~81%). Highly metro-concentrated.",
        "Performance signal": "Node ROAS ~4.2x on ~Rs2.2L spend — proven but heavily under-funded. Charging basket AOV Rs10-12k = 4-4.8x brand AOV.",
        "Read": "Male-led, older & professional desk/WFH buyer. Category is nascent — job is part category-creation. Expansion = 35-44 higher-AOV professional, premium Android Qi2, and women/gifting.",
    },
    "personas": [
        {
            "name": "WFH Desk Professional",
            "tg": "Dominant",
            "who": "25-34 male working professional, desk/WFH, back-to-back calls, phone charging on the desk all day.",
            "trigger": "Building a proper desk setup; tired of a cable snaking across the desk.",
            "need": "Clean, always-on desk charging that keeps the phone topped up during calls.",
            "pain": "A cable across the desk, phone flat on the table, unplugging to take a call.",
            "angle": "Pain point + Desired outcome",
            "sku": "Surge Rs4,499 / Loft 65W station",
            "reach": "'Cable-free desk' aesthetic reels, WFH/desk-setup & Apple-interest audiences, feed",
            "funnel": [
                ("TOFU", "Unaware", "Tethered to a cable, hasn't questioned it", "Curiosity / Pain point",
                 "Your desk has a Rs2L laptop and a Rs10 cable ruining the whole look.", "PAS",
                 '"Your desk is 90% sorted. Then there\'s the cable."'),
                ("MOFU", "Problem-aware", "Cable clutter + phone flat on desk", "Pain point",
                 "Unplugging to pick up a call, plugging back in, a cable you fight with all day.", "PAS",
                 '"How many times a day do you plug in?"'),
                ("MOFU", "Solution-aware", "Wants clean wireless desk charging", "Desired outcome",
                 "Snap-on wireless charging that stands your phone up for calls — cable-free desk, done.", "BAB",
                 '"Charge without touching a cable."'),
                ("BOFU", "Product-aware", "Comparing Surge / Loft vs Anker / Belkin", "Feature / Comparison",
                 "Surge: Qi2 MagSafe, 15W, stands your phone; Loft 65W docks phone + buds + laptop on one desk.", "FAB",
                 '"One dock. Whole desk. Zero cables."'),
                ("BOFU", "Most-aware", "Ready, wants the easy yes", "Offer / Trust",
                 "Untether your desk. Free delivery, 1-year warranty, easy returns.", "4 U's",
                 '"Cable-free desk. Ships free."'),
            ],
        },
        {
            "name": "iPhone MagSafe Owner",
            "tg": "Dominant",
            "who": "Premium iPhone 15-17 owner who charges wirelessly but with a slow, non-certified pad.",
            "trigger": "Just got a new iPhone; wants the fastest, cleanest MagSafe charging.",
            "need": "Genuinely fast, certified MagSafe charging that snaps on perfectly.",
            "pain": "'MagSafe-compatible' pads are slow, mis-align and aren't actually Qi2-certified.",
            "angle": "Authority / Feature",
            "sku": "Surge Rs4,499 (Qi2 MagSafe)",
            "reach": "iPhone-model & Apple-ecosystem audiences, retargeting Pro viewers, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Assumes all wireless charging is the same", "Curiosity",
                 "Your iPhone can charge fast wirelessly. Your charger is probably holding it back.", "BAB",
                 '"Your wireless charger is slower than you think."'),
                ("MOFU", "Problem-aware", "Frustrated by slow / misaligning pad", "Pain point",
                 "Phone slides off the pad overnight, wakes up at 60% — 'wireless' shouldn't mean slow.", "PAS",
                 '"Woke up to a half-charged phone again?"'),
                ("MOFU", "Solution-aware", "Learns Qi2-certified ≠ 'MagSafe-compatible'", "Authority / Comparison",
                 "Not every 'MagSafe' charger is Qi2-certified — certification means real 15W and verified safety.", "FAB",
                 '"MagSafe-compatible isn\'t Qi2-certified. Here\'s why it matters."'),
                ("BOFU", "Product-aware", "Comparing Surge vs alternatives", "Feature / Authority",
                 "Surge: Qi2-certified, true 15W, precise magnetic snap, safe fast charging.", "FAB",
                 '"Snap on. 15W. Certified."'),
                ("BOFU", "Most-aware", "Ready, wants reassurance", "Offer / Trust",
                 "The charger your iPhone deserves. 1-year warranty, free delivery, 30-day returns.", "4 U's",
                 '"Real 15W. 1-year warranty."'),
            ],
        },
        {
            "name": "Multi-Device Declutterer",
            "tg": "Dominant",
            "who": "Owns phone + buds + watch; travels between desk and home; hates carrying three chargers.",
            "trigger": "Sick of three chargers and three cables for three devices.",
            "need": "One dock/charger that powers phone, buds and watch together.",
            "pain": "Three cables, three bricks, a tangle at the desk and in the bag.",
            "angle": "Curiosity / Comparison",
            "sku": "Surge Foldaway Rs7,999 (3-in-1) / Node ecosystem",
            "reach": "Comparison carousels, multi-device & Apple-ecosystem audiences, feed",
            "funnel": [
                ("TOFU", "Unaware", "Doesn't realise a 3-in-1 exists", "Curiosity",
                 "You have three devices and three chargers. What if you needed just one?", "BAB",
                 '"Count the chargers in your bag right now."'),
                ("MOFU", "Problem-aware", "Annoyed by three-charger clutter", "Pain point",
                 "Phone brick, watch puck, buds cable — a knot of chargers at every desk and in every bag.", "PAS",
                 '"Three devices. Three cables. One mess."'),
                ("MOFU", "Solution-aware", "Wants one 3-in-1 solution", "Comparison / Desired outcome",
                 "One 3-in-1 dock charges phone + buds + watch at once — folds flat for travel.", "FAB",
                 '"One dock. Phone, buds, watch. Done."'),
                ("BOFU", "Product-aware", "Comparing capacity & fold", "Feature",
                 "Surge Foldaway: Qi2.2, 3 devices at once, foldable for the bag — desk at home, dock on the road.", "FAB",
                 '"3 devices, one fold-flat dock."'),
                ("BOFU", "Most-aware", "Ready, packing / setting up", "Offer",
                 "Replace three chargers with one. Free delivery, 1-year warranty.", "4 U's",
                 '"One dock replaces three. Ships free."'),
            ],
        },
        {
            "name": "Senior Desk Professional (35-44)",
            "tg": "Expansion",
            "who": "35-44 established professional (under-indexed), higher AOV, home-office, values a premium setup.",
            "trigger": "Investing in a serious, permanent home-office; wants a premium charging station.",
            "need": "A premium, permanent one-dock desk solution that looks and feels high-end.",
            "pain": "Cheap chargers cheapen an otherwise premium desk; too many single-purpose gadgets.",
            "angle": "Authority / Desired outcome",
            "sku": "Loft 65W station / Surge Foldaway Rs7,999",
            "reach": "35-44 professional & high-AOV audiences, premium desk-setup content, feed",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't invested in a proper charging dock", "Curiosity / Story",
                 "You've built a serious desk. The charging still looks like an afterthought.", "BAB",
                 '"A premium desk deserves more than a cheap pad."'),
                ("MOFU", "Problem-aware", "Too many single-purpose chargers", "Pain point",
                 "A puck here, a brick there — a premium desk cluttered with mismatched charging gadgets.", "PAS",
                 '"Your desk cost a lot. Your charging looks cheap."'),
                ("MOFU", "Solution-aware", "Wants one premium station", "Desired outcome / Authority",
                 "Loft 65W: one dock that powers the whole desk — phone, buds, laptop — in a premium finish.", "FAB",
                 '"The one-dock desk, done properly."'),
                ("BOFU", "Product-aware", "Evaluating build & power", "Feature / Authority",
                 "65W total, Qi2.2 fast wireless, aluminium build — a permanent, premium centrepiece.", "FAB",
                 '"65W. One dock. Built to last."'),
                ("BOFU", "Most-aware", "Ready, wants a considered buy", "Offer / Trust",
                 "Invest once, charge everything. 1-year warranty, free delivery.", "4 U's",
                 '"The last charger your desk needs."'),
            ],
        },
        {
            "name": "Premium Android Qi2 Switcher",
            "tg": "Expansion",
            "who": "Samsung S / OnePlus flagship owner — Qi2 magnetic charging now works on premium Android too.",
            "trigger": "Heard the new flagship supports Qi2 magnets; wants MagSafe-style charging on Android.",
            "need": "A certified Qi2 magnetic charger that finally works properly with a flagship Android.",
            "pain": "Wireless charging on Android has meant slow pads and no magnets — until Qi2.",
            "angle": "Curiosity / Comparison",
            "sku": "Surge Rs4,499 (Qi2, future-ready for Android)",
            "reach": "Premium-Android flagship-owner audiences, Qi2 education content, feed",
            "funnel": [
                ("TOFU", "Unaware", "Thinks magnetic charging is iPhone-only", "Curiosity",
                 "Magnetic snap-on charging was an iPhone thing. Your flagship Android just caught up.", "BAB",
                 '"Galaxy owners: MagSafe-style charging is finally yours."'),
                ("MOFU", "Problem-aware", "Stuck with slow Android wireless pads", "Pain point",
                 "Slide-around pads, slow speeds, no magnets — Android wireless charging has been a downgrade.", "PAS",
                 '"Android wireless charging always felt like an afterthought."'),
                ("MOFU", "Solution-aware", "Learns Qi2 brings magnets to Android", "Comparison / Desired outcome",
                 "Qi2 brings certified magnetic 15W to Samsung S & OnePlus — the same snap-on experience.", "FAB",
                 '"Qi2 = magnets + speed, now on Android."'),
                ("BOFU", "Product-aware", "Checking Qi2 fit for his phone", "Feature",
                 "Surge: Qi2-certified magnetic charging, true 15W, works with your flagship Android today.", "FAB",
                 '"Snap on your Galaxy. Real 15W."'),
                ("BOFU", "Most-aware", "Ready, wants fit assurance", "Offer / Trust",
                 "Future-ready Qi2 charging for Android. 1-year warranty, free delivery, easy returns.", "4 U's",
                 '"Qi2-ready for Android. Ships free."'),
            ],
        },
        {
            "name": "Aesthetic Woman & Gifter",
            "tg": "Expansion",
            "who": "Design-led woman (19% today) + gifting buyer; drawn by colour, finish and a premium giftable object.",
            "trigger": "Curating a pretty desk / nightstand, or looking for a premium, useful gift for a phone person.",
            "need": "A charger that looks beautiful on a nightstand — or a safe, premium, universally-useful gift.",
            "pain": "Chargers are ugly black pucks; tech gifts feel boring or too personal.",
            "angle": "Desired outcome (design) + Offer",
            "sku": "Surge Rs4,499 in premium finishes / gift bundles",
            "reach": "Female-creator aesthetic desk films, women lookalikes, gifting-season & occasion audiences",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; design/gift provocation", "Curiosity",
                 "Your nightstand is aesthetic. The charger on it is not.", "BAB",
                 '"The ugliest thing on your desk is charging your phone."'),
                ("MOFU", "Problem-aware", "Ugly charger / gifting dilemma", "Pain point",
                 "A black plastic puck ruins a pretty setup — and 'useful' tech gifts are usually boring.", "PAS",
                 '"Gifting a phone person? You\'re overthinking it."'),
                ("MOFU", "Solution-aware", "Discovers a beautiful, giftable charger", "Desired outcome",
                 "A premium, colour-matched charger that looks unreal on a desk — and gifts even better.", "FAB",
                 '"A charger you\'d actually leave on display."'),
                ("BOFU", "Product-aware", "Choosing finish / as a gift", "Desired outcome / Social proof",
                 "Surge in premium finishes: snaps on, charges fast, gift-ready packaging.", "FAB",
                 '"Which finish? (and it gift-wraps beautifully)"'),
                ("BOFU", "Most-aware", "Ready to buy / gift (incl. bulk)", "Offer",
                 "Gift it sorted — free delivery, 1-year warranty. Corporate gifting available in bulk.", "4 U's",
                 '"Gift sorted. Free delivery, 1-yr warranty."'),
            ],
        },
    ],
}
