# Phone Cases — Stack ecosystem
CATEGORY = {
    "key": "Phone Cases",
    "tab": "Cases",
    "title": "STACK · PHONE CASES",
    "snapshot": {
        "Category & moat": "DO's largest category (Rs47Cr FY26 -> Rs91Cr FY27). Premium designer band Rs999-1,699. Moat = the Stack MODULAR MagSafe ecosystem (case + wallet + grip + lanyard + bag + charging), not price. Case = the low-ticket acquisition hook.",
        "Hero SKUs / price": "Stack Rs1,499 · Stack Signature Rs1,699 · Basics + colour SKUs · Stride 2.0 (rugged/leather) · Stack for Samsung (Qi2-ready)",
        "Dominant TG — gender": "Male 76% / Female 24%",
        "Dominant TG — age": "25-34 = 51% (core) · 18-24 = 26% · 35-44 = 16% · 45+ = 6%   (18-34 = 78%)",
        "Dominant TG — geography": "MH 22 · KA 15 · DL 8 · GJ 8 · UP 7 · TN 6 · TG 6 · HR 6  (top-8 ~78%). Metro, iPhone-led.",
        "Performance signal": "Creator campaigns 5.3-6.2x ROAS vs 3.6x BAU; Reels ~4.3x; DPA retargeting 4.1x. 52% repeat base.",
        "Read": "Male-skewed, overwhelmingly 18-34, metro, Apple-first, identity-driven 'wearable tech-fashion'. Expansion headroom = women (24->35%), premium Android, and the under-penetrated 35-44 professional.",
    },
    "personas": [
        {
            "name": "Young iPhone Loyalist",
            "tg": "Dominant",
            "who": "25-34, metro male, latest iPhone, design-conscious, treats the case as part of his identity. The 51% core.",
            "trigger": "Just bought/upgraded an iPhone; wants a case that looks as good as the phone.",
            "need": "A design-led case that protects without hiding the phone, and signals taste.",
            "pain": "Generic cases look cheap and every case looks the same on the shelf.",
            "angle": "Desired outcome (design) + Feature",
            "sku": "Stack Rs1,499 / Signature Rs1,699",
            "reach": "Creator design reels, Apple-interest & iPhone-model audiences, Reels & Explore",
            "funnel": [
                ("TOFU", "Unaware", "Scrolling; hasn't thought of the case as a design object", "Curiosity / Story",
                 "Your iPhone is the best-designed thing you own. Your case shouldn't ruin it.", "BAB",
                 '"You spent Rs1L on a phone. Then hid it in this?"'),
                ("MOFU", "Problem-aware", "Annoyed that his current case looks generic", "Pain point",
                 "Bulky, yellowing, forgettable — most cases downgrade the phone they're meant to protect.", "PAS",
                 '"Every case on the shelf looks the same. Yours doesn\'t have to."'),
                ("MOFU", "Solution-aware", "Comparing design-led cases", "Desired outcome / Comparison",
                 "Stack is a design object first — precise fit, premium finish, MagSafe built in.", "FAB",
                 '"A case designed like the phone it\'s on."'),
                ("BOFU", "Product-aware", "Comparing Stack vs Spigen / Casetify", "Feature / Authority",
                 "Stack: full MagSafe fit, drop-tested protection, and it snaps into a whole modular system.", "FAB",
                 '"Protection you\'d expect. Design you didn\'t."'),
                ("BOFU", "Most-aware", "Ready, wants the nudge", "Offer / Social proof",
                 "Loved by thousands of iPhone owners. Free delivery, easy returns, lifetime of style.", "4 U's",
                 '"Your phone\'s new signature. Ships free."'),
            ],
        },
        {
            "name": "Gen-Z Self-Expressor",
            "tg": "Dominant",
            "who": "18-24, student / early-career, style-first, follows drops, buys on colour and vibe. Peer-validated.",
            "trigger": "New colour drop or a creator wearing it; wants to refresh the look cheaply.",
            "need": "Self-expression on a budget; a case that matches the mood and the feed.",
            "pain": "Premium cases feel out of budget; cheap ones look cheap.",
            "angle": "Curiosity / Desired outcome",
            "sku": "Basics + colour SKUs",
            "reach": "Lo-fi UGC, colour-drop hype reels, younger lookalikes, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Passive scroll, drop provocation", "Curiosity",
                 "Your phone case is an outfit. Why are you wearing the same one every day?", "BAB",
                 '"POV: your case doesn\'t match a single fit you own."'),
                ("MOFU", "Problem-aware", "Wants a refresh but thinks premium = expensive", "Pain point",
                 "Cool cases shouldn't cost a bomb. And cheap ones fall apart in a month.", "PAS",
                 '"Broke but want a good case? Read this."'),
                ("MOFU", "Solution-aware", "Realises there's an affordable design line", "Desired outcome",
                 "Basics: design-led colours, real protection, entry price — the start of your Stack.", "FAB",
                 '"Design-led cases that actually fit the budget."'),
                ("BOFU", "Product-aware", "Picking a colour, peer-checking", "Desired outcome / Social proof",
                 "New-season colourways, MagSafe-ready, snaps into grips & lanyards you can add later.", "FAB",
                 '"Which colour are you? (case drop haul)"'),
                ("BOFU", "Most-aware", "Wants validation before buying", "Social proof / Offer",
                 "Rated by thousands of Gen-Z buyers. Grab the colour before it sells out.", "4 U's",
                 '"Selling fast. Pick your colour."'),
            ],
        },
        {
            "name": "MagSafe System Builder",
            "tg": "Dominant",
            "who": "Existing DO / MagSafe user who wants everything to snap together — case, wallet, grip, lanyard, bag.",
            "trigger": "Already owns a Stack case; sees the wallet/grip and wants the full setup.",
            "need": "One modular system where every accessory clicks on and off the phone.",
            "pain": "Mismatched accessories that don't work together; loose cards & cables.",
            "angle": "Feature / Desired outcome",
            "sku": "Stack + wallet / grip / lanyard / bag add-ons",
            "reach": "'Build your Stack' demo reels, retargeting Stack buyers, PDP & cart",
            "funnel": [
                ("TOFU", "Unaware", "Doesn't know an integrated case-system exists", "Curiosity",
                 "What if your case, wallet, grip and bag all snapped onto one phone?", "BAB",
                 '"One magnet. Your whole setup."'),
                ("MOFU", "Problem-aware", "Juggling separate accessories that don't fit together", "Pain point",
                 "A stick-on wallet here, a random grip there — nothing actually works as a system.", "PAS",
                 '"Your accessories don\'t talk to each other. Ours do."'),
                ("MOFU", "Solution-aware", "Learns Stack is modular", "Desired outcome / Comparison",
                 "Stack is a system: start with the case, snap on wallet, grip, lanyard, bag as you need them.", "FAB",
                 '"Build your phone setup like Lego."'),
                ("BOFU", "Product-aware", "Configuring the add-ons", "Feature",
                 "Every Stack add-on is MagSafe-native and designed to match — click on, click off, all day.", "FAB",
                 '"Snap on a wallet. Snap on a bag. Same case."'),
                ("BOFU", "Most-aware", "Ready to complete the setup", "Offer",
                 "Finish your Stack — bundle the case + wallet + grip and save. Free delivery.", "4 U's",
                 '"Complete your Stack. Bundle & save."'),
            ],
        },
        {
            "name": "Design-First Woman",
            "tg": "Expansion",
            "who": "18-34 woman, treats the phone as a fashion accessory; cares about colour, bags & lanyards as the look.",
            "trigger": "Curating an outfit / bag aesthetic; sees a female creator styling a phone-as-accessory.",
            "need": "A phone setup that reads as fashion — aesthetic colours, crossbody lanyard, matching bag.",
            "pain": "Case ranges are built for men; nothing coordinates with her style.",
            "angle": "Desired outcome (fashion) + Social proof",
            "sku": "Stack colours + bags / lanyards",
            "reach": "Female-creator aesthetic films, women lookalikes, Reels & Explore",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; fashion provocation", "Curiosity / Story",
                 "Your bag, your shoes, your phone — one of these isn't styled. Yet.", "BAB",
                 '"Your phone is the last un-styled thing you carry."'),
                ("MOFU", "Problem-aware", "Frustrated cases aren't made for her look", "Pain point",
                 "Chunky black cases don't go with anything. The phone deserves to be part of the outfit.", "PAS",
                 '"Why is every case designed for a man?"'),
                ("MOFU", "Solution-aware", "Discovers phone-as-accessory range", "Desired outcome",
                 "Aesthetic colourways + a crossbody phone lanyard = hands-free, styled, done.", "FAB",
                 '"The phone-as-accessory era is here."'),
                ("BOFU", "Product-aware", "Choosing colour + lanyard/bag", "Desired outcome / Social proof",
                 "Stack in her palette, snap-on crossbody lanyard, matching mini bag — a coordinated look.", "FAB",
                 '"Style your phone like you style your fits. (GRWM)"'),
                ("BOFU", "Most-aware", "Wants peer validation", "Social proof / Offer",
                 "Loved by women who style everything. Pick your colour, add the lanyard, ships free.", "4 U's",
                 '"The setup on your FYP. Ships free."'),
            ],
        },
        {
            "name": "Premium Android Switcher",
            "tg": "Expansion",
            "who": "Galaxy S / OnePlus owner who assumed the good design-led cases are iPhone-only.",
            "trigger": "Wants a premium case for a new flagship Android and can't find one that isn't rugged/ugly.",
            "need": "A design-led, Qi2-ready case that actually fits Galaxy / OnePlus.",
            "pain": "Android premium case options are thin — mostly clear TPU or bulky armour.",
            "angle": "Curiosity / Comparison",
            "sku": "Stack for Samsung S (Qi2-ready)",
            "reach": "Android flagship-owner audiences, comparison carousels, feed",
            "funnel": [
                ("TOFU", "Unaware", "Assumes design cases are iPhone-only", "Curiosity",
                 "The nicest cases were always 'iPhone only'. Not anymore.", "BAB",
                 '"Galaxy owners: this one\'s finally for you."'),
                ("MOFU", "Problem-aware", "Sick of clear TPU or armour bricks", "Pain point",
                 "Your flagship Android deserves better than a clear case or a rugged brick.", "PAS",
                 '"You bought a flagship. Then a Rs200 clear case?"'),
                ("MOFU", "Solution-aware", "Discovers Stack now fits Android", "Comparison / Desired outcome",
                 "Same design language, same modular system — now cut for Galaxy S & OnePlus, Qi2-ready.", "FAB",
                 '"The design case iPhone users brag about — now yours."'),
                ("BOFU", "Product-aware", "Checking model fit & Qi2", "Feature",
                 "Precise model fit, MagSafe/Qi2 magnets built in, snaps into the same Stack ecosystem.", "FAB",
                 '"Made for your model. Magnets built in."'),
                ("BOFU", "Most-aware", "Ready, wants reassurance on fit", "Offer / Trust",
                 "Guaranteed fit for your Galaxy/OnePlus. Free delivery, easy returns.", "4 U's",
                 '"Guaranteed fit. Or free return."'),
            ],
        },
        {
            "name": "Understated Professional / Gifter",
            "tg": "Expansion",
            "who": "35-44 professional (the under-penetrated pocket); values understated premium, leather & durability; also buys as a gift.",
            "trigger": "Upgrading a daily-carry, or buying a thoughtful, useful gift for an iPhone person.",
            "need": "A grown-up, understated case in premium materials — or a safe premium gift.",
            "pain": "Loud designs feel juvenile; tech gifts are either boring or too personal.",
            "angle": "Authority / Desired outcome",
            "sku": "Signature Rs1,699 / Stride 2.0 / leather lines",
            "reach": "Studio-lifestyle reels, 35+ professional audiences, gifting LP & occasion audiences",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't considered a material upgrade", "Curiosity / Story",
                 "At some point a phone case should feel like the rest of your grown-up kit.", "BAB",
                 '"The case that finally matches your watch."'),
                ("MOFU", "Problem-aware", "Current case feels juvenile / worn", "Pain point",
                 "Loud plastic doesn't fit the boardroom. And gifting tech always feels like a gamble.", "PAS",
                 '"Still carrying a case from three phones ago?"'),
                ("MOFU", "Solution-aware", "Wants understated premium / a safe gift", "Desired outcome / Authority",
                 "Signature & Stride: leather and precision-milled finishes — quietly premium, gift-ready.", "FAB",
                 '"Understated. Premium. Actually useful."'),
                ("BOFU", "Product-aware", "Evaluating as upgrade or gift", "Authority / Desired outcome",
                 "Full-grain leather, MagSafe fit, gift-ready packaging — a case that reads as a proper gift.", "FAB",
                 '"A gift they\'ll use every single day."'),
                ("BOFU", "Most-aware", "Ready to buy / gift", "Offer",
                 "Gift it sorted — premium finish, free delivery, easy returns. Corporate gifting in bulk.", "4 U's",
                 '"Gift sorted. Ships free, returns easy."'),
            ],
        },
    ],
}
