# Desk Accessories — Platform collection + Bar organiser
CATEGORY = {
    "key": "Desk Accessories",
    "tab": "Desk Accessories",
    "title": "PLATFORM · DESK ACCESSORIES",
    "snapshot": {
        "Category & moat": "Smallest & highest-AOV of the desk trio (Rs13Cr FY26 -> Rs26Cr FY27), lowest spend = most headroom. Premium designer Rs1,499-3,999. Moat = a coordinated design-led desk SYSTEM at India prices vs mass plastic / priced-out global premium.",
        "Hero SKUs / price": "Platform collection & Bar desk organiser (heroes) · desk mats · mouse pads · trays/coasters · laptop/monitor/phone stands · wood/leatherette premium lines",
        "Dominant TG — gender": "Male 69% / Female 31%  (most balanced of the desk trio)",
        "Dominant TG — age": "25-34 = 47% (core) · 35-44 = 21% (strongest tail) · 18-24 = 18% · 45+ = 13%   (18-34 = 66%)",
        "Dominant TG — geography": "MH 22 · KA 12 · DL 9 · GJ 8 · HR 7 · UP 6 · TN 6 · TG 6  (top-8 ~76%). Metro & professional-led.",
        "Performance signal": "'Bar Desk Organiser' ~3.1x ROAS; Meta AOV ~Rs3,365 (highest of the trio); lowest spend = scale headroom.",
        "Read": "Urban professional / hybrid-WFH worker for whom a tidy aesthetic desk is a productivity & identity statement. Expansion = 35-44 senior professional (premium materials), women (31->40%), and corporate/B2B team setups & gifting.",
    },
    "personas": [
        {
            "name": "Young WFH Professional",
            "tg": "Dominant",
            "who": "25-34 hybrid/WFH professional (the 47% core); works from a home desk, cares how it looks on calls.",
            "trigger": "Setting up / upgrading a home-office desk; wants it tidy and put-together.",
            "need": "A coordinated desk setup that looks intentional and keeps the essentials in place.",
            "pain": "A messy, mismatched desk that looks unprofessional on video calls.",
            "angle": "Pain point + Desired outcome",
            "sku": "Platform collection + Bar organiser",
            "reach": "Desk-makeover creator reels, WFH/professional 25-44 audiences, feed & Pinterest",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't thought of the desk as a designed space", "Curiosity / Story",
                 "You spend 8 hours a day at your desk. When did you last actually design it?", "BAB",
                 '"Your desk is your most-used room. And it shows."'),
                ("MOFU", "Problem-aware", "Messy, mismatched desk", "Pain point",
                 "Cables, clutter and random plastic trays — your desk looks nothing like the setups you save.", "PAS",
                 '"On every call, your desk is in frame. Yikes."'),
                ("MOFU", "Solution-aware", "Wants a coordinated desk look", "Desired outcome",
                 "Design your desk as a system: mat, organiser and stands that finally match.", "FAB",
                 '"Design your desk, don\'t just fill it."'),
                ("BOFU", "Product-aware", "Comparing the Platform system vs single items", "Feature / Comparison",
                 "Platform + Bar organiser + mat = a coordinated desk that styles together, at India prices.", "FAB",
                 '"A desk that looks designed, not assembled."'),
                ("BOFU", "Most-aware", "Ready, wants the nudge", "Offer",
                 "Your best desk yet. Free delivery, easy returns — start with the mat + organiser.", "4 U's",
                 '"Design your desk. Ships free."'),
            ],
        },
        {
            "name": "Aesthetic Desk-Setup Enthusiast",
            "tg": "Dominant",
            "who": "Desk-tour / r-battlestations type who curates and posts the setup; New-Year-reset motivated.",
            "trigger": "New-Year productivity reset or a desk-tour that inspires a makeover.",
            "need": "Statement, aesthetic desk pieces that elevate the whole setup and photograph well.",
            "pain": "The setup is 90% there but cheap accessories break the aesthetic.",
            "angle": "Desired outcome (aesthetic) + Social proof",
            "sku": "Premium desk mat + Platform + stands",
            "reach": "Desk-tour & setup creators, aesthetic-setup lookalikes, Reels & Pinterest",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; setup inspiration", "Curiosity / Story",
                 "The desks you keep saving all have one thing in common: nothing on them is random.", "BAB",
                 '"Why do the best desk setups all look so intentional?"'),
                ("MOFU", "Problem-aware", "Cheap pieces ruin the aesthetic", "Pain point",
                 "One ugly plastic tray or a bare desk drags down an otherwise clean setup.", "PAS",
                 '"Your setup is 90% there. It\'s the details."'),
                ("MOFU", "Solution-aware", "Discovers coordinated statement pieces", "Desired outcome",
                 "A premium desk mat anchors the look; the Platform system ties every piece together.", "FAB",
                 '"The desk mat that makes the whole setup."'),
                ("BOFU", "Product-aware", "Choosing finishes & pieces", "Desired outcome / Social proof",
                 "Coordinated colours & materials, statement mat, tidy Platform organiser — a setup worth posting.", "FAB",
                 '"Desk glow-up: before vs after."'),
                ("BOFU", "Most-aware", "New-Year reset, ready", "Social proof / Offer",
                 "New year, new desk. Loved by setup obsessives — free delivery, easy returns.", "4 U's",
                 '"New year, new desk. Ships free."'),
            ],
        },
        {
            "name": "Student Desk Glow-up",
            "tg": "Dominant",
            "who": "18-24 student, study-from-home, wants an aesthetic desk on a budget; entry into the system.",
            "trigger": "Exam season / new semester; wants a study desk that motivates and looks good.",
            "need": "Affordable aesthetic desk pieces that make studying feel better.",
            "pain": "Premium desk gear feels out of budget; the study desk is dull and messy.",
            "angle": "Curiosity / Desired outcome",
            "sku": "Desk mats / mouse pads (entry rung)",
            "reach": "Study-with-me & desk glow-up UGC, 18-24 lookalikes, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; study-desk provocation", "Curiosity",
                 "A better study desk actually makes you want to sit down and study. Weird but true.", "BAB",
                 '"POV: your study desk is why you never study there."'),
                ("MOFU", "Problem-aware", "Dull, messy study desk, tight budget", "Pain point",
                 "Bare table, tangled charger, nothing that makes you want to open a book.", "PAS",
                 '"Studying at a desk that depresses you?"'),
                ("MOFU", "Solution-aware", "Finds affordable aesthetic pieces", "Desired outcome",
                 "Start with a desk mat + mouse pad — instant glow-up, entry price, room to build later.", "FAB",
                 '"Desk glow-up for the price of a pizza."'),
                ("BOFU", "Product-aware", "Choosing colours", "Feature / Offer",
                 "Aesthetic colours, quality feel, the affordable entry into a desk you'll keep upgrading.", "FAB",
                 '"Small change. Whole new desk."'),
                ("BOFU", "Most-aware", "Ready, budget buy", "Offer",
                 "Glow up your desk today. Free delivery, easy returns.", "4 U's",
                 '"Desk glow-up. Ships free."'),
            ],
        },
        {
            "name": "Senior Professional (35-44)",
            "tg": "Expansion",
            "who": "35-44 senior professional (under-indexed, core desk buyer); values understated premium & craft.",
            "trigger": "Building a permanent, serious home-office; wants materials that signal seniority.",
            "need": "Understated premium desk pieces in wood/leatherette that signal craft, not gadgetry.",
            "pain": "Colourful 'aesthetic' desk gear feels junior; wants quietly premium.",
            "angle": "Authority / Desired outcome",
            "sku": "Premium wood / leatherette Platform & mats",
            "reach": "35-44 professional & high-AOV audiences, material close-up content, feed",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't upgraded to premium materials", "Curiosity / Story",
                 "At a certain point, your desk should feel as considered as your work.", "BAB",
                 '"The desk of someone who\'s clearly senior."'),
                ("MOFU", "Problem-aware", "Aesthetic gear feels junior / cheap", "Pain point",
                 "Bright pads and plastic trays don't match a corner office or a 15-year career.", "PAS",
                 '"Still working off a Rs200 plastic tray?"'),
                ("MOFU", "Solution-aware", "Wants understated premium materials", "Desired outcome / Authority",
                 "Wood and leatherette desk pieces — quietly premium, built to last, made to be seen.", "FAB",
                 '"Understated. Premium. Grown-up."'),
                ("BOFU", "Product-aware", "Evaluating build & material", "Authority / Feature",
                 "Full-grain leatherette mat, real-wood Platform, precise craft — a desk that signals seniority.", "FAB",
                 '"Craft you can feel. Every day."'),
                ("BOFU", "Most-aware", "Ready, considered buy", "Offer / Trust",
                 "Invest in a desk that lasts. Free delivery, easy returns, warranty.", "4 U's",
                 '"Premium desk, done right. Ships free."'),
            ],
        },
        {
            "name": "Design-First Woman",
            "tg": "Expansion",
            "who": "Woman professional / student (31% today) who treats the workspace as an aesthetic she owns.",
            "trigger": "Refreshing her workspace; sees a female creator's pastel/coordinated desk.",
            "need": "A coordinated, aesthetic workspace in her palette — colour-matched sets, not male-default gear.",
            "pain": "Desk accessories default to black/grey and ignore how she wants her space to feel.",
            "angle": "Desired outcome (aesthetic) + Social proof",
            "sku": "Coordinated mats / trays / organisers in aesthetic colourways",
            "reach": "Female-creator desk films, women lookalikes, Reels & Pinterest",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; aesthetic-workspace provocation", "Curiosity / Story",
                 "Your workspace should feel like yours — not like a default office.", "BAB",
                 '"Every desk accessory comes in black. Where\'s your colour?"'),
                ("MOFU", "Problem-aware", "Gear is male-default, not aesthetic", "Pain point",
                 "Grey trays and black mats don't match the space you actually want to work in.", "PAS",
                 '"Why is every desk set designed to be invisible?"'),
                ("MOFU", "Solution-aware", "Finds colour-coordinated sets", "Desired outcome",
                 "Pastel and colour-matched mats, trays and organisers that coordinate into a look.", "FAB",
                 '"A workspace as considered as your feed."'),
                ("BOFU", "Product-aware", "Choosing palette", "Desired outcome / Social proof",
                 "Coordinated sets in her palette — the aesthetic desk women actually want to build.", "FAB",
                 '"Desk makeover in [her colour]. (GRWM)"'),
                ("BOFU", "Most-aware", "Wants validation", "Social proof / Offer",
                 "Loved by women who design their space. Free delivery, easy returns.", "4 U's",
                 '"The desk on your Pinterest. Ships free."'),
            ],
        },
        {
            "name": "Corporate / B2B Buyer",
            "tg": "Expansion",
            "who": "HR / admin / founder buying team desk setups or premium desk gifts in bulk.",
            "trigger": "New-hire onboarding, office setup, or a festive/appreciation gifting cycle.",
            "need": "Premium, coordinated desk kits for teams and impressive, useful gifts at scale.",
            "pain": "Corporate gifts are forgettable; team desks look cheap and inconsistent.",
            "angle": "Desired outcome + Offer",
            "sku": "Platform / organiser sets (bulk) + gift bundles",
            "reach": "Corporate-gifting LP, B2B & founder/HR audiences, LinkedIn-style targeting",
            "funnel": [
                ("TOFU", "Unaware", "Gifting/setup as a chore", "Curiosity",
                 "The best corporate gift isn't a mug or a hamper — it's something they use every workday.", "BAB",
                 '"Still gifting your team another mug?"'),
                ("MOFU", "Problem-aware", "Forgettable gifts / inconsistent desks", "Pain point",
                 "Generic gifts get forgotten; mismatched team desks make the office look unfinished.", "PAS",
                 '"Onboarding gifts nobody remembers by Friday."'),
                ("MOFU", "Solution-aware", "Wants premium coordinated kits", "Desired outcome",
                 "Coordinated desk kits — premium, useful, brandable — that make teams and gifts look sorted.", "FAB",
                 '"A gift they\'ll use at 9am every day."'),
                ("BOFU", "Product-aware", "Evaluating bulk options", "Authority / Feature",
                 "Bulk-ready Platform & organiser sets, custom branding, consistent premium look across a team.", "FAB",
                 '"Team desks, sorted. Gift-ready in bulk."'),
                ("BOFU", "Most-aware", "Ready to order at scale", "Offer",
                 "Premium desk gifting at scale — bulk pricing, custom branding, on-time delivery.", "4 U's",
                 '"Corporate gifting, sorted. Talk to us."'),
            ],
        },
    ],
}
