# Tech Organisers — Park Tech Kit + folios + pouches + cable organisers
CATEGORY = {
    "key": "Tech Organisers",
    "tab": "Tech Organisers",
    "title": "PARK · TECH ORGANISERS",
    "snapshot": {
        "Category & moat": "DO's most efficient Meta engine (Rs12Cr FY26 -> Rs23Cr FY27). Premium designer Rs1,499-2,999. Moat = design + a coordinated EDC SYSTEM at India prices, not single pouches. Lead line: 'the kit that organises your everyday tech'.",
        "Hero SKUs / price": "Park Tech Kit (hero) · tech pouches · folios · cable organisers · MacBook adapter cases · keychains · planners · premium leather folios/kits (super-premium)",
        "Dominant TG — gender": "Male 71% / Female 29%",
        "Dominant TG — age": "25-34 = 48% (core) · 18-24 = 27% · 35-44 = 15% · 45+ = 10%   (18-34 = 75%)",
        "Dominant TG — geography": "MH 22 · KA 14 · DL 9 · GJ 7 · HR 6 · UP 6 · TN 6 · TG 6  (top-8 ~76%). Metro & professional-led.",
        "Performance signal": "'Park Tech Kit' ~4.1x ROAS — the most efficient of the three (proven creators: Techiesaksham, Vault). 'Your best engine.'",
        "Read": "Urban professional & traveller EDC buyer who treats a tech organiser as a productivity necessity. Expansion = 35-44 senior professional (leather folios), frequent travellers, women (29->38%), and corporate gifting.",
    },
    "personas": [
        {
            "name": "Young Professional EDC",
            "tg": "Dominant",
            "who": "25-34 male professional (the 48% core); carries chargers, cables, adapters daily; wants it sorted.",
            "trigger": "New laptop / new job; tired of a bag full of loose cables and chargers.",
            "need": "One coordinated kit that holds all his everyday tech in order.",
            "pain": "A tangled mess of cables and adapters loose at the bottom of the bag.",
            "angle": "Pain point + Desired outcome",
            "sku": "Park Tech Kit",
            "reach": "EDC 'organise with me' creator reels, professional 25-34 audiences, feed",
            "funnel": [
                ("TOFU", "Unaware", "Lives with cable chaos, hasn't fixed it", "Curiosity / Story",
                 "Everything you carry is premium. It's all just floating loose in one bag.", "BAB",
                 '"Your bag is a Rs2L device and a Rs0 organisation system."'),
                ("MOFU", "Problem-aware", "Frustrated hunting for cables/adapters", "Pain point",
                 "Digging for the right cable, a tangled charger, an adapter you can never find.", "PAS",
                 '"How long did you spend finding a cable today?"'),
                ("MOFU", "Solution-aware", "Wants a coordinated kit", "Desired outcome",
                 "The Park Tech Kit gives every cable, charger and adapter its own place — grab and go.", "FAB",
                 '"Your everyday tech, finally organised."'),
                ("BOFU", "Product-aware", "Comparing kit vs single pouches", "Feature / Comparison",
                 "Park is a system: modular pouches, cable loops, device slots — coordinated, not a random bag.", "FAB",
                 '"The kit that organises your everyday tech."'),
                ("BOFU", "Most-aware", "Ready, wants the nudge", "Offer",
                 "Sort your carry today. Free delivery, easy returns, warranty.", "4 U's",
                 '"Get sorted. Ships free."'),
            ],
        },
        {
            "name": "Frequent Traveller",
            "tg": "Dominant",
            "who": "Frequent flyer / road-tripper who packs multiple devices and dreads cable chaos on trips.",
            "trigger": "Packing for a trip; hates untangling cables and losing adapters in the hotel.",
            "need": "One travel kit that keeps every device and cable organised across a trip.",
            "pain": "Cables tangle in the suitcase; adapters get lost; repacking every stop.",
            "angle": "Comparison / Ultra-specific",
            "sku": "Park Tech Kit / travel tech pouches",
            "reach": "Travel-pack creator demos, travel & airport-intent audiences, feed",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; relatable packing pain", "Story / Curiosity",
                 "Every trip starts with untangling the same ball of cables from last trip.", "BAB",
                 '"Unpacking a knot of cables in the hotel. Again."'),
                ("MOFU", "Problem-aware", "Cables tangle, adapters lost", "Pain point",
                 "One tangled pouch, a missing adapter, a charger you left at the last hotel.", "PAS",
                 '"How many chargers have you left behind?"'),
                ("MOFU", "Solution-aware", "Wants a travel-organised kit", "Comparison / Desired outcome",
                 "One kit, a slot for every cable and device — pack once, find everything, lose nothing.", "FAB",
                 '"One kit. Every trip. Nothing lost."'),
                ("BOFU", "Product-aware", "Comparing capacity & layout", "Feature / Comparison",
                 "Park Tech Kit: labelled slots, secure cable loops, device protection — carry-on organised.", "FAB",
                 '"Pack your tech like a pro traveller."'),
                ("BOFU", "Most-aware", "Ready, packing now", "Offer",
                 "Pack sorted before your next trip. Free delivery, easy returns.", "4 U's",
                 '"Trip-ready tech. Ships free."'),
            ],
        },
        {
            "name": "Student Cable-Chaos Fixer",
            "tg": "Dominant",
            "who": "18-24 student / early-career (27% secondary); charger and earphone chaos in the bag, tight budget.",
            "trigger": "Bag is a mess of tangled cables; wants a cheap fix that looks good.",
            "need": "An affordable way to declutter chargers, cables and earphones.",
            "pain": "Tangled earphones and chargers; nice organisers feel out of budget.",
            "angle": "Curiosity / Desired outcome",
            "sku": "Cable organisers / tech pouches (entry rung)",
            "reach": "Declutter UGC, 18-24 lookalikes, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; declutter provocation", "Curiosity",
                 "The most satisfying thing you'll do this week: untangle your bag for good.", "BAB",
                 '"POV: your charger and earphones are one knot now."'),
                ("MOFU", "Problem-aware", "Tangled chargers, tight budget", "Pain point",
                 "Every time you reach in, it's a tangle — and the good organisers seem too pricey.", "PAS",
                 '"Fighting your own charger cable daily?"'),
                ("MOFU", "Solution-aware", "Finds affordable organisers", "Desired outcome",
                 "A cable organiser + pouch sorts the chaos for the price of a couple of coffees.", "FAB",
                 '"Declutter your bag for under Rs1,500."'),
                ("BOFU", "Product-aware", "Choosing colours / size", "Feature / Offer",
                 "Right-sized pouches, cable loops, quality feel — the affordable entry into the Park system.", "FAB",
                 '"Small pouch. Big difference."'),
                ("BOFU", "Most-aware", "Ready, budget buy", "Offer",
                 "Sort the chaos today. Free delivery, easy returns.", "4 U's",
                 '"Untangle your bag. Ships free."'),
            ],
        },
        {
            "name": "Senior Professional Folio (35-44)",
            "tg": "Expansion",
            "who": "35-44 senior professional (the biggest untapped pocket); wants a premium leather folio & kit.",
            "trigger": "Wants a grown-up daily carry that signals craft; upgrading from a fabric pouch.",
            "need": "Understated premium leather folios and kits for the daily professional carry.",
            "pain": "Fabric pouches feel junior; wants leather that matches his level.",
            "angle": "Authority / Desired outcome",
            "sku": "Premium leather folio / kit",
            "reach": "35-44 professional audiences, material close-up reels, gifting audiences",
            "funnel": [
                ("TOFU", "Unaware", "Hasn't upgraded from a fabric pouch", "Curiosity / Story",
                 "Your carry says a lot about you before you say a word. What's yours saying?", "BAB",
                 '"The folio of someone who\'s clearly senior."'),
                ("MOFU", "Problem-aware", "Fabric pouch feels junior", "Pain point",
                 "A cheap nylon pouch next to a leather notebook and a nice pen — one of these is off.", "PAS",
                 '"Still carrying your tech in a freebie pouch?"'),
                ("MOFU", "Solution-aware", "Wants premium leather EDC", "Desired outcome / Authority",
                 "A full-grain leather folio and kit — organised, understated, built to age well.", "FAB",
                 '"Leather that organises, and impresses."'),
                ("BOFU", "Product-aware", "Evaluating material & layout", "Authority / Feature",
                 "Premium leather, structured device slots, coordinated with the Park system, gift-ready.", "FAB",
                 '"Craft you carry every day."'),
                ("BOFU", "Most-aware", "Ready, considered buy", "Offer / Trust",
                 "Carry premium, sorted. Free delivery, easy returns, warranty.", "4 U's",
                 '"Premium EDC. Ships free."'),
            ],
        },
        {
            "name": "Work-From-Anywhere Woman",
            "tg": "Expansion",
            "who": "Woman professional (29% today) who works from cafes, flights, home; wants aesthetic + organised.",
            "trigger": "Wants a work-from-anywhere kit that's as aesthetic as it is functional.",
            "need": "Aesthetic, coordinated kits and folios that look good and keep tech sorted on the move.",
            "pain": "Tech organisers are boxy, black and built for men.",
            "angle": "Desired outcome (aesthetic) + Social proof",
            "sku": "Aesthetic folios / kits in coordinated colourways",
            "reach": "Female-creator work-from-anywhere films, women lookalikes, Reels",
            "funnel": [
                ("TOFU", "Unaware", "Scroll; work-from-anywhere provocation", "Curiosity / Story",
                 "Your work moves with you. Your tech should travel as neatly as you do.", "BAB",
                 '"Work-from-anywhere looks great — until you open your bag."'),
                ("MOFU", "Problem-aware", "Organisers are boxy & male-default", "Pain point",
                 "Every tech organiser is a black brick — nothing that fits how she wants her bag to look.", "PAS",
                 '"Why is every tech pouch designed to be ugly?"'),
                ("MOFU", "Solution-aware", "Finds aesthetic coordinated kits", "Desired outcome",
                 "Aesthetic folios and kits that coordinate — organised tech that actually looks good.", "FAB",
                 '"A work kit as put-together as you are."'),
                ("BOFU", "Product-aware", "Choosing palette / pieces", "Desired outcome / Social proof",
                 "Coordinated colourways, slim folios, smart slots — the work-from-anywhere kit women want.", "FAB",
                 '"What\'s in my work-from-anywhere bag."'),
                ("BOFU", "Most-aware", "Wants validation", "Social proof / Offer",
                 "Loved by women who work everywhere. Free delivery, easy returns.", "4 U's",
                 '"The kit on your feed. Ships free."'),
            ],
        },
        {
            "name": "Corporate Gifting Buyer",
            "tg": "Expansion",
            "who": "HR / admin / founder buying branded tech kits for onboarding or festive gifting at scale.",
            "trigger": "New-hire onboarding kits or a festive/appreciation gifting cycle.",
            "need": "Premium, practical, brandable tech kits that make a great impression at scale.",
            "pain": "Corporate gifts are forgettable; onboarding swag ends up in a drawer.",
            "angle": "Desired outcome + Offer",
            "sku": "Park kits / folios (bulk, brandable) Rs1,500-3,500",
            "reach": "Corporate-gifting LP, B2B & HR/founder audiences, LinkedIn-style targeting",
            "funnel": [
                ("TOFU", "Unaware", "Gifting as a chore", "Curiosity",
                 "The best onboarding gift isn't a t-shirt — it's the kit they use at their desk from day one.", "BAB",
                 '"Still onboarding people with a branded t-shirt?"'),
                ("MOFU", "Problem-aware", "Forgettable / unused gifts", "Pain point",
                 "Most corporate gifts get forgotten in a week; the budget's spent, the impression isn't made.", "PAS",
                 '"Your last gifting spend — remembered by anyone?"'),
                ("MOFU", "Solution-aware", "Wants premium brandable kits", "Desired outcome",
                 "Premium, practical, brandable tech kits people actually use — every workday.", "FAB",
                 '"A gift they\'ll use at their desk daily."'),
                ("BOFU", "Product-aware", "Evaluating bulk & branding", "Authority / Feature",
                 "Bulk-ready Park kits & folios, custom branding, consistent premium look — Rs1,500-3,500.", "FAB",
                 '"Onboarding kits, sorted. Brandable in bulk."'),
                ("BOFU", "Most-aware", "Ready to order at scale", "Offer",
                 "Premium tech gifting at scale — bulk pricing, custom branding, on-time delivery.", "4 U's",
                 '"Corporate gifting, sorted. Talk to us."'),
            ],
        },
    ],
}
